credentials:
  usernames:
    makafui-kwawu:
      email: sm.kwawu@gmail.com
      logged_in: False # Will be managed automatically
      name: Success Makafui Kwawu
      password: '123456' # Will be hashed automatically
cookie:
  expiry_days: 0
  key: cookie_signature_key # Must be string
  name: cookie_name
pre-authorized:
  emails:
  - success.kwawu@azubiafrica.org
users: